site_name: Iridium
repo_url: https://github.com/IridiumIdentity/iridium

plugins:
  - search
  - mike
theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.png
  logo: images/iridiumxl.png

extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-XQP7070X67
