
version: '3.8'

services:

  mariadb:
    image: mariadb:10.6.11
    container_name: mariadb-identity
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: iridium
      MYSQL_DATABASE: identities
      MYSQL_USER: identity-api
      MYSQL_PASSWORD: "sug4rn3ss&"
    networks:
      - iridium

networks:
  iridium:
    driver: bridge
