name: Build Iridium Core Server Docker Image Snapshot

on:
  pull_request:
    branches: [ "*" ]


env:
  NAMESPACE: iridiumidentity
  IMAGE_NAME: iridium-core-server

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
     - uses: actions/checkout@v3
       
     - uses: actions/setup-java@v1.4.4
       with:
         java-version: 17
         java-package: jdk
         architecture: x64
         server-id: maven
     - run: ./tools/scripts/build-docker.sh ${{ env.NAMESPACE }} ${{ env.IMAGE_NAME }}

     
      
   
