name: Build Iridium - every pull request

on:
  pull_request:
    branches: [ "*" ]


env:
  REGISTRY: ghcr.io
  NAMESPACE: iridiumidentity
  IMAGE_NAME: iridium-core-server

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
     - uses: actions/checkout@v3
     - name: Log in to the Container registry
       uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
       with:
         registry: ${{ env.REGISTRY }}
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
       
     - uses: actions/setup-java@v1.4.4
       with:
         java-version: 17
         java-package: jdk
         architecture: x64
         server-id: maven
     - run: mvn clean package
     - name: set up node 18
       uses: actions/setup-node@v3
       with:
         node-version: '18.x'
     - name: install node deps
       run: npm ci
       working-directory: ./iridium-angular-client
     - name: lint angular clients
       run: npm run lint-all
       working-directory: ./iridium-angular-client
     - name: build angular clients
       run: npm run build-all
       working-directory: ./iridium-angular-client

     
      
   
