name: Build Iridium Core Server Docker Image Snapshot

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v3
     - name: Build Iridium Docker image
       run: ./tools/scripts/build-docker.sh 

     
      
   
