name: Build - every pull request

on:
  pull_request:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
     - uses: actions/checkout@v3
       
     - uses: actions/setup-java@v1.4.4
       with:
         java-version: 17
         java-package: jdk
         architecture: x64
         server-id: maven
     - run: mvn clean package
     - uses: actions/checkout@v3
     - name: set up node 18
       uses: actions/setup-node@v3
       with:
         node-version: '18.x'
     - name: install node deps
       run: npm ci
       working-directory: ./iridium-angular-client
     - name: lint angular clients
       run: npm run lint
       working-directory: ./iridium-angular-client
     - name: build angular clients
       run: npm run build-all
       working-directory: ./iridium-angular-client

     
      
   
