name: Publish iridium artifacts based on a tag

on:
  push:

    tags: [ "v*" ]

env:
  NAMESPACE: iridiumidentity
  IMAGE_NAME: iridium-core-server

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set version
        id: vars
        run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}

      # set up java
      - uses: actions/setup-java@v1.4.4
        with:
          java-version: 17
          java-package: jdk
          architecture: x64
          server-id: maven

      # build and publish Docker
      - name: build docker image
        run: ./tools/scripts/build-and-push-docker.sh ${{ env.NAMESPACE }} ${{ env.IMAGE_NAME }} ${{ env.version }}

      # build and publish binary distro
      - name: upload tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: iridium-${{ env.version }}-bin
          path: iridium-cli/target/iridium-*-bin.tar.gz

      # set up node
      - name: set up node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      # build and publish Angular
      - name: install angular cli
        run: npm install -g @angular/cli@15
        working-directory: ./iridium-angular-client
      - name: npm install deps
        run:  npm install
        working-directory: ./iridium-angular-client
      - name: build ngx-iridium-client
        run: ng build ngx-iridium-client
        working-directory: ./iridium-angular-client
      - name: publish angular library
        run: npm publish --access public
        working-directory: ./iridium-angular-client/dist/ngx-iridium-client
        # build and publish next.js
      - name: install deps next.js
        run: npm install
        working-directory: ./iridium-client-nextjs
      - name: build next.js client
        run: npm run build-lib
        working-directory: ./iridium-client-nextjs
      - name: publish next.js client
        run: npm publish --access public
        working-directory: ./iridium-client-nextjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


