name: Publish nightly artifacts

on:
  push:
    branches:
      - main

env:
  NAMESPACE: iridiumidentity
  IMAGE_NAME: iridium-core-server-nightly

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set version
        id: vars
        run: echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}

      - uses: actions/setup-java@v1.4.4
        with:
          java-version: 17
          java-package: jdk
          architecture: x64
          server-id: maven

      - name: build docker image
        run: ./tools/scripts/build-and-push-docker.sh ${{ env.NAMESPACE }} ${{ env.IMAGE_NAME }} ${{ env.version }}

      - name: upload tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: iridium-${{ env.version }}-bin
          path: iridium-cli/target/iridium-*-bin.tar.gz



