name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
        working-directory: ./site
      - run: pip install mike
        working-directory: ./site
      - run: |
          git fetch origin gh-pages --depth=1
          git config user.name github-actions
          git config user.email github-actions@iridium.software
          mike deploy --push 0.1.4

        working-directory: ./site
